# pull official base image
FROM node:18 AS builder
# set working directory
WORKDIR /app
# install app dependencies
# copies package.json and yarn.lock to Docker environment
COPY package.json ./
COPY yarn.lock ./
# Installs all node packages
RUN yarn install 
# Copies everything over to Docker environment
COPY ./ ./
RUN yarn run build

#Stage 2
#######################################
# pull the official nginx:1.19.0 base image
FROM nginx:latest
# copies React to the container directory
# Set working directory to nginx resources directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=builder /app/dist/ ./
#Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
