FROM huggingface/transformers-pytorch-gpu

WORKDIR /app

COPY . /app

RUN apt-get update -y && apt-get install -y \
    build-essential \
    git \
    libffi-dev \
    libssl-dev \
    libc-dev \
    make \
    wget 

RUN cd /tmp && git clone https://github.com/edenhill/librdkafka.git && \
  cd librdkafka && git checkout tags/v2.3.0 && \
  ./configure && make && make install && \
  cd ../ && rm -rf librdkafka

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && ln -s /usr/bin/python3 /usr/bin/python

RUN python -c "from transformers import AutoTokenizer, AutoModel; tokenizer = AutoTokenizer.from_pretrained('allenai/specter'); model = AutoModel.from_pretrained('allenai/specter')" 

RUN apt-get remove -y \
    build-essential \
    git \
    libffi-dev \
    libssl-dev \
    libc-dev \
    make \
    wget \
&& apt-get autoremove -y \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
