name: deployment-flow


on:
  push:
    tags:
      - '*'
      
run-name: deployment of ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: deploy on server
        uses: appleboy/ssh-action@v1.0.1
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script_stop: true
          script: |
            cd ${{ secrets.SERVER_FRONTEND_PATH }}
            git pull
            docker compose stop
            dos2unix start_services.sh
            bash ./start_services.sh ${{ secrets.SERVER_IP }} ${{ secrets.QDRANT_COLLECTION_NAME }} ${{ secrets.KAGGLE_TOPIC }} ${{ secrets.COLS_TO_CRAWL}}
