name: frontend-deployment

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**/*'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PASSPHRASE: ${{secrets.PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "$SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.SERVER_FRONTEND_PATH }}
          git pull
          cd ..
          docker-compose up -d --build
          EOF
